config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins

  root "home#index"
  
  resources :categories, only: [:show]
  resources :products, only: [:show]

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  get "admin", to: "admin#index"
  get "cart", to: "carts#show"
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_admin_order, only: %i[ show edit update destroy ]

  # GET /admin/orders or /admin/orders.json
  def index
    @not_fullfiled_orders = Order.where(fullfiled: false).order(created_at: :asc)
    @fullfiled_orders = Order.where(fullfiled: true).order(created_at: :asc)
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
    @admin_order = Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
    @admin_order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_path, status: :see_other, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Order.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def admin_order_params
      params.require(:order).permit(:customer_email, :fullfiled, :total, :address)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, admin_order], class: "contents") do |form| %>
  <% if admin_order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>

      <ul class="list-disc ml-6">
        <% admin_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_email %>
    <%= form.text_field :customer_email, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": admin_order.errors[:customer_email].none?, "border-red-400 focus:outline-red-600": admin_order.errors[:customer_email].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :fullfiled %>
    <%= form.checkbox :fullfiled, class: ["block shadow rounded-md border outline-none mt-2 h-5 w-5", {"border-gray-400 focus:outline-blue-600": admin_order.errors[:fullfiled].none?, "border-red-400 focus:outline-red-600": admin_order.errors[:fullfiled].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :total %>
    <%= form.number_field :total, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": admin_order.errors[:total].none?, "border-red-400 focus:outline-red-600": admin_order.errors[:total].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": admin_order.errors[:address].none?, "border-red-400 focus:outline-red-600": admin_order.errors[:address].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Customer email:</strong>
    <%= order.customer_email %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Fullfiled:</strong>
    <%= order.fullfiled %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <%= order.total %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= order.address %>
  </p>

  <% if order.order_products.any? %>
    <h2 class="font-bold text-2xl">Products</h2>
    <% order.order_products.each do |order_product| %>
      <%= order_product.product.name %>
      <%= order_product.product.size %>
      <%= order_product.product.quantity %>
    <% end %>
  <% end %>
</div>

app/views/admin/orders/edit.html.erb
<% content_for :title, "Editing order" %>

<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", admin_order: @admin_order %>

  <%= link_to "Show this order", [:admin, @admin_order], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/index.html.erb
<% content_for :title, "Orders" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to "New order", new_admin_order_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <h2 class="font-bold text-2xl">Unfunfilled Orders</h2>

  <div class="bg-white rounded-lg shadow">
    <table class="min-w-full">
      <thead>
        <tr class="border-b">
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">ID</th>
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Email</th>
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Address</th>
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Total</th>
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Actions</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <% @not_fullfiled_orders.each do |order| %>
          <tr>
            <td class="px-6 py-4 text-sm text-gray-800"><%= link_to order.id, [:admin, order], class: "underline" %></td>
            <td class="px-6 py-4 text-sm text-gray-800"><%= order.customer_email %></td>
            <td class="px-6 py-4 text-sm text-gray-600"><%= order.address %></td>
            <td class="px-6 py-4 text-sm text-gray-600"><%= order.total %></td>
            <td class="px-6 py-4 text-sm">
              <div class="flex space-x-2">
                <%= link_to 'Edit', edit_admin_order_path(order), 
                    class: 'rounded-md px-3.5 py-2.5 text-white bg-[#FF9119] hover:bg-[#FF9119]/80 text-white block font-medium' %>
                <%= link_to 'Delete', admin_order_path(order), 
                    method: :delete, 
                    data: { confirm: 'Are you sure?' }, 
                    class: 'rounded-md px-3.5 py-2.5 bg-red-600 hover:bg-red-500 text-white block font-medium' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <h2 class="font-bold text-2xl">Fullfilled Orders</h2>

  <div class="bg-white rounded-lg shadow">
    <table class="min-w-full">
      <thead>
        <tr class="border-b">
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">ID</th>
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Email</th>
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Address</th>
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Total</th>
          <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Actions</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <% @fullfiled_orders.each do |order| %>
          <tr>
            <td class="px-6 py-4 text-sm text-gray-800"><%= link_to order.id, [:admin, order], class: "underline" %></td>
            <td class="px-6 py-4 text-sm text-gray-800"><%= order.customer_email %></td>
            <td class="px-6 py-4 text-sm text-gray-600"><%= order.address %></td>
            <td class="px-6 py-4 text-sm text-gray-600"><%= order.total %></td>
            <td class="px-6 py-4 text-sm">
              <div class="flex space-x-2">
                <%= link_to 'Edit', edit_admin_order_path(order), 
                    class: 'rounded-md px-3.5 py-2.5 text-white bg-[#FF9119] hover:bg-[#FF9119]/80 text-white block font-medium' %>
                <%= link_to 'Delete', admin_order_path(order), 
                    method: :delete, 
                    data: { confirm: 'Deseja deletar a ordem?' }, 
                    class: 'rounded-md px-3.5 py-2.5 bg-red-600 hover:bg-red-500 text-white block font-medium' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/admin/orders/new.html.erb
<% content_for :title, "New order" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New order</h1>

  <%= render "form", admin_order: @admin_order %>

  <%= link_to "Back to orders", admin_orders_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/admin/orders/show.html.erb
<% content_for :title, "Showing order" %>

<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
    <% end %>

  <h1 class="font-bold text-4xl">Showing order</h1>

    <%= render @admin_order %>

  <%= link_to "Edit this order", edit_admin_order_path(@admin_order), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to orders", admin_orders_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this order", admin_order_path(@admin_order), method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>