config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins

  root "home#index"
  
  resources :categories, only: [:show]
  resources :products, only: [:show]

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  get "admin", to: "admin#index"
  get "cart", to: "carts#show"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 50, 50 ]
    attachable.variant :medium, resize_to_limit: [ 100, 100 ]
  end
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :stocks
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 50, 50 ]
    attachable.variant :medium, resize_to_limit: [ 100, 100 ]
  end
  has_many :order_products
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!
  def index
    @orders = Order.where(fullfiled: false).order(created_at: :desc).take(5)

    @quick_stats = {
        sales: Order.where(created_at: Time.now.midnight..Time.now).count,
        revenue: Order.where(created_at: Time.now.midnight..Time.now).sum(:total).round(),
        avg_sale: Order.where(created_at: Time.now.midnight..Time.now).average(:total).round(),
        per_sale: OrderProduct.joins(:order).where(
            orders: {
                created_at: Time.now.midnight..Time.now
            }
        ).average(:quantity)
    }

    @orders_by_day = Order.where("created_at > ?", Time.now - 7.days).order(:created_at)
    @orders_by_day = @orders_by_day.group_by { |order| order.created_at.to_date }

    @revenue_by_day = @orders_by_day.map { |day, orders| [ day.strftime("%A"), orders.sum(&:total) ] }

    if @revenue_by_day.count < 7
        days_of_week = [ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" ]
        data_hash = @revenue_by_day.to_h
        current_day = Date.today.strftime("%A")
        current_day_index = days_of_week.index(current_day)
        next_day_index = (current_day_index + 1) % days_of_week.length

        ordered_days_with_current_last = days_of_week[next_day_index..-1] + days_of_week[0..next_day_index]
        complete_ordered_array_with_current_last = ordered_days_with_current_last.map {
            |day| [ day, data_hash.fetch(day, 0) ]
        }

        @revenue_by_day = complete_ordered_array_with_current_last

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
        @category = Category.find(params[:id])
        @products = @category.products
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @main_categories = Category.take(5)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def show
        @product = Product.find(params[:id])
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/stocks_helper.rb
module Admin::StocksHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.erb
<h1>Admin</h1>

<div class="flex justify-between flex-wrap mt-8 w-full items-center max-w-4xl">
    <h2 class="text-2xl text-gray-800 font-medium mb-4">Daily Stats</h2>
    
    <div class="flex gap-10 flex-col md:flex-row justify-between w-full">
        <div class="max-w-sm rounded overflow-hidden shadow-lg bg-gradient-to-r from-gray-400 to-gray-300">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2 text-gray-800">Revenue</div>
                <p class="text-gray-800 text-base">
                    R$ <%= @quick_stats[:revenue] ? number_to_currency(@quick_stats[:revenue], unit: '', separator: ',', delimiter: '.') : "0" %>
                </p>
            </div>
        </div>

        <div class="max-w-sm rounded overflow-hidden shadow-lg bg-gradient-to-r from-gray-400 to-gray-300">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2 text-gray-800">Total Sales</div>
                <p class="text-gray-800 text-base">
                    R$ <%= @quick_stats[:sales] ? (@quick_stats[:sales]).to_s : "0" %>
                </p>
            </div>
        </div>

        <div class="max-w-sm rounded overflow-hidden shadow-lg bg-gradient-to-r from-gray-400 to-gray-300">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2 text-gray-800">Avg Sales</div>
                <p class="text-gray-800 text-base">
                    R$ <%= @quick_stats[:avg_sale] ? number_to_currency(@quick_stats[:avg_sale], unit: '', separator: ',', delimiter: '.') : "0" %>
                </p>
            </div>
        </div>

        <div class="max-w-sm rounded overflow-hidden shadow-lg bg-gradient-to-r from-gray-400 to-gray-300">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2 text-gray-800">Items / Sales</div>
                <p class="text-gray-800 text-base">
                    <%= @quick_stats[:per_sale].to_i%>
                </p>
            </div>
        </div>
    </div>

    <div class="my-8 w-full">
        <h2 class="text-2xl text-gray-800 font-medium mb-4">Revenue</h2>
        <div class="w-full" data-controller="dashboard" data-dashboard-revenue-value="<%= @revenue_by_day.to_json%>">
            <canvas id="revenueChart"></canvas>
        </div>
    </div>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex">
      <nav class="flex">
        <div class="w-64 p-4 h-screen bg-gray-600 sticky top-0">
            <div class="flex">
                <%= image_tag "food.jpg", class: 'w-16' %>
                <h1 class="text-md py-2 text-gray-50 font-bold hidden md:block">Ecomm Admin</h1>
            </div>
            <ul class="flex flex-col text-gray-50">
                <li>
                    <%= link_to admin_path, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                        <%= icon('fa-solid', 'gauge-high') %> 
                        <span class="hidden md:inline-block">Dashboard</span>

                    <% end %>
                </li>
                <li>
                    <%= link_to admin_products_path, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                        <%= icon('fa-solid', 'cart-shopping') %> 
                        <span class="hidden md:inline-block">Product</span>

                    <% end %>
                </li>
                <li>
                    <%= link_to admin_categories_path, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                        <%= icon('fa-solid', 'list') %> 
                        <span class="hidden md:inline-block">Categories</span>

                    <% end %>
                </li>
                <li>
                    <%= link_to admin_orders_path, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                        <%= icon('fa-solid', 'truck-fast') %> 
                        <span class="hidden md:inline-block">Orders</span>

                    <% end %>
                </li>
                <li>
                    <%= link_to destroy_admin_session_path, data: { "turbo_method": "delete", "turbo_confirm": "Gostaria fazer logout?" }, class:"block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                        <%= icon('fa-solid', 'sign-out') %> 
                        <span class="hidden md:inline-block">Logout</span>

                    <% end %>
                </li>
            </ul>
        </div>
      </nav>
      <div class="w-full p-8 p-16 ">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Foodapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="container mx-auto mt-28 sm:px-2 lg:px-2">
      <%= yield %>
    </main>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-gray-800 text-white">
    <div class="max-2-6xl max-auto px-4 py-10 md:py-20">
        <div class="xl:grid xl:grid-cols-3 xl:gap-8">
            <div class="space-y-8 xl:col-span-1">
                <h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase">
                    About Ecomm
                </h3>
                <p class="text-white leading-6">
                    Marketplace específico para vendas de produtos 
                </p>
            </div>
            <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
                <div class="md:grid md:grid-cols-2 md:gap-8">
                    <div>
                        <h3 class="text-sm font-semibold text-gray-200 tracking wider uppercase">
                            Quick Links
                        </h3>
                        <ul class="mt-4 space-y-4">
                            <li>
                                <%= link_to "Home", root_path, class:"text-base leading-6 text-white hover:text-gray-100"%>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="mt-8 mb-8 md:grid md:grid-cols-2 md:gap-8">
                <div>
                    <h3 class="text-sm font-semibold tracking-wider uppercase text-gray-200">
                        Contact
                    </h3>
                    <ul class="mt-4 space-y-4">
                        <li>
                            <p class="text-base leading-6 text-white">
                                Ecom Test <br>
                                Ecommerce, Test
                            </p>
                        </li>
                        <li>
                            <p class="text-base leading-6 text-white">
                                E-mail: suport@test.com
                            </p>
                        </li>
                        <li>
                            <p class="text-base leading-6 text-white">
                                Phone: (11)4002-8922
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="border-t border-gray-700">
                <div class="max-w-6xl mx-auto px-4 py-6 md:flex md:items-center md:justify-between">
                    <p class="mt-6 text-base leading-6 text-gray-400 md:mt-0 md:order-1">
                        &copy; <%= Time.now.year%> Ecomm, Inc. All rights reserved.
                    </p> 
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="fixed w-full top-0 bg-gray-100 z-10 py-4">
  <div class=" mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-between">
        <div class="hidden sm:flex items-center justify-center">
          <div class="flex space-x-10">
              <%= link_to 'Shop', root_path, class: 'text-gray-500 hover:underline py-2 rounded-md text-md font-medium' %>
          </div>
        </div>
        <div class="flex-shrink-0 flex items-center">
          <%= link_to root_path do %>
              <%= image_tag 'food.jpg', class: 'block lg:hidden h-20 w-auto'%>
          <% end %>
          <%= link_to root_path do %>
              <%= image_tag 'food.jpg', class: 'block lg:block h-20  w-auto'%>
          <% end %>
        </div>
        <div class="hidden sm:flex sml:ml-6 items-center justify-center">
          <div class="flex space-x-10">
            <%= link_to cart_path, class: "text-gray-500 hover:underline py-2 rounded-md text-md font-medium" do %>
                <%= icon 'fa-solid', 'shopping-cart' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>